### ISSUE TITLE
Automation enhancements

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-sandbox#60]
The sandbox CLI behaves a little different when compared with the other Akamai CLIs packages making it harder to use it to automate tasks.

Can we do some small enhancements to limit the usage of standard input?

For example:
1) when you use the "sandbox create" command, there is a request to answer in the terminal Yes/No ("Would you like the Sandbox Client to proxy these to the destination defined in the Akamai config? Yes"). It would help automation if that would be indicated as a parameter of the create command
2) The start command (akamai sandbox start) never completes and instead dumps a continuous stream of text to the standard output. This is not very DevOps friendly and it will be better to offer a parameter to indicate where the output should go (and send it to a default file -and show its name in the output- if the parameter is missing). For example the start parameter could output on success something like: (either in text, or better yet in JSON format)
---clip---
config="/launchpad/cli/.akamai-cli/cache/sandbox-cli/sandboxes/javier/config.json"
logging.path="/launchpad/cli/.akamai-cli/cache/sandbox-cli/sandboxes/javier/logs"
logging.config="/launchpad/cli/.akamai-cli/cache/sandbox-cli/sandbox-client-1.1.7-RELEASE/conf/logback.xml"
Sandbox Client running on port: 9550
---clap---

**Comment by kporowski** [comment]
Already implemented.
