### ISSUE TITLE
Java JDK version compatibility

### ISSUE THREAD

**Issue by nmckay77** [akamai/cli-sandbox#78]
The installation documentation https://learn.akamai.com/en-us/webhelp/sandbox/sandbox-user-guide/GUID-B1CA65F4-08BD-4878-9237-D358DB22CB06.html specifies Java version 8+ is required but there appears to be a compatibility issue with at least JDK 15. If there is a specific JDK dependency that should be called out in the installation instruction, preferably with a link to install the latest working version.

**Comment by krzyk** [comment]
@nmckay77 Thanks, we are already working on it.

**Comment by brianbento** [comment]
Any news on this? Pretty sure I'm running into this bug.

**Comment by herzykj** [comment]
the bug should be resolved with the latest 1.4.0 version #93 that was deployed today.
To use the latest CLI version, please run
`akamai update sandbox`
