### ISSUE TITLE
SwitchKey doesnt work when multiple query strings exist

### ISSUE THREAD

**Issue by vreddhi** [akamai/cli-sandbox#87]
The switchkey doesnt work when there are multiple query strings

**Comment by krzyk** [comment]
@vreddhi Could you give an example how you use it? If you could give us a working example it would be great.

(I'm a bit unclear what does "multiple query strings" mean.)

**Comment by vreddhi** [comment]
I was referring to the query string the REST endpoint that the CLI actually makes calls to:

Here is the fix for this: 

https://github.com/vreddhi/cli-sandbox/commit/1abfe32ab254749c399335f165c7d244d46bbccd
https://github.com/vreddhi/cli-sandbox/commit/0853b321e264825dd2d6ae9e30df35f83717fc31

**Comment by krzyk** [comment]
@vreddhi Thanks.
But do you have the exact CLI command that you used to trigger the issue, it would be helpful for QAs to validate.

**Comment by herzykj** [comment]
the bug should be resolved with the latest 1.4.0 version #93 that was deployed today.
To use the latest CLI version, please run
`akamai update sandbox`
