### ISSUE TITLE
`rotate-jwt` doesn't update `client.json`

### ISSUE THREAD

**Issue by lukaszczerpak** [akamai/cli-sandbox#88]
When `rotate-jwt` command is invoked, `'.datastore` file gets updated with a new token but sandboxes that are already created do not get updated their `client.json` where the same JWT is stored. As a result, Sandbox Client throws an error about expired token. Manual copy/paste from `.datastore` to respective `client.json` fixes the problem.

**Comment by herzykj** [comment]
Fortunately that was already fixed by pull request #86 . We will release the new cli-sandbox version probably in the next week.

**Comment by herzykj** [comment]
the bug should be resolved with the latest 1.4.0 version #93 that was deployed today.
To use the latest CLI version, please run
`akamai update sandbox`
